# Generated by Django 4.2.3 on 2023-08-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_maraton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
